### ISSUE TITLE
string (C# Reference)

### ISSUE THREAD

**Issue by ArtemIsaev13** [dotnet/docs.ru-ru#141]
On the page 
https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/string
you can see the text:

**_The advantage of verbatim strings is that escape sequences are not processed, which makes it easy to write, for example, a fully qualified file name:
@"c:\Docs\Source\a.txt"  // rather than "c:\\Docs\\Source\\a.txt"_**

Maybe you mean this text:
**_@"c:/Docs/Source/a.txt"  // rather than "c:\\Docs\\Source\\a.txt"_**
?

best regards
Isaev Artem
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 67b95029-3bf2-c56d-48ab-be7ad1f43762
* Version Independent ID: a5f74e00-3f77-804d-f47d-26caa05bfc40
* Content: [string (Справочник по C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/string)
* Content Source: [docs/csharp/language-reference/keywords/string.md](https://github.com/dotnet/docs.ru-ru/blob/live-sxs/docs/csharp/language-reference/keywords/string.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #8616](https://github.com/dotnet/docs/issues/8616) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @ArtemIsaev13 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/8616.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
