### ISSUE TITLE
example for C# does not work

### ISSUE THREAD

**Issue by MinistrBob** [dotnet/docs.ru-ru#168]
I corrected it
if (e.KeyCode == Keys.Return)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: dcd32f6d-4a54-b4a9-643e-1bfa30f98d4d
* Version Independent ID: f42b5de3-7407-4d1c-8504-f07620f57c04
* Content: [Как выполнить Обнаружить, когда нажата клавиша ВВОД](https://docs.microsoft.com/ru-ru/dotnet/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed)
* Content Source: [docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #10270](https://github.com/dotnet/docs/issues/10270) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @MinistrBob 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/10270.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
