### ISSUE TITLE
Reorganize

### ISSUE THREAD

**Issue by gerich-home** [dotnet/docs.ru-ru#182]
Good article, but can be slightly reorganized.

It feels like comparison with existing frameworks (.Net framework, Mono) gives reader lots of understanding about the position of .Net Core. Maybe it needs to be moved closer to the top of article?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [Сведения о .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11276](https://github.com/dotnet/docs/issues/11276) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @gerich-home 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11276

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
