### ISSUE TITLE
The 1st code example does not make any changes

### ISSUE THREAD

**Issue by AndyDmy** [dotnet/docs.ru-ru#187]
1. The phrase "_You could also change the SearchDirectoryArgs to a struct, if you make one more **change**:_" implies that the code example after it has some differences. But it's completely the same, as on the previous page.
2. Without a specific example it is unclear how this **change** must be done to the constructor.
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2cb74e28-b327-0f9f-5fa5-882a00d10ceb
* Version Independent ID: 645a8a12-a026-bee9-7501-e8ec4a32ce31
* Content: [Обновленный шаблон событий .NET Core](https://docs.microsoft.com/ru-ru/dotnet/csharp/modern-events)
* Content Source: [docs/csharp/modern-events.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/modern-events.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @AndyDmy

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11648

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
