### ISSUE TITLE
404 Result for Algorithms` links

### ISSUE THREAD

**Issue by DmitriyBolgarov** [dotnet/docs.ru-ru#190]
Good Day. Is it ok, that most of the links for Algorighms redirect me to 404 page? Could anybody please make them innactive if not exists yet.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Задачи машинного обучения. Использование ML.NET](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/resources/tasks#feedback)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11727](https://github.com/dotnet/docs/issues/11727) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DmitriyBolgarov

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11727

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
