### ISSUE TITLE
Incorrect url in an example

### ISSUE THREAD

**Issue by Kezzya** [dotnet/docs.ru-ru#225]
myClient.OpenRead("http://www.contoso.com/index.htm"); 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2cf9d0b8-7f12-9cda-abe9-35488f15296d
* Version Independent ID: 12edf729-7210-2644-6315-7f24a9ca1cc4
* Content: [Практическое руководство. Запрос веб-страницы и получение результатов в виде потока](https://docs.microsoft.com/ru-ru/dotnet/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream)
* Content Source: [docs/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by srvbpigh** [comment]
Hello, @Kezzya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #14714](https://github.com/dotnet/docs/issues/14714) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Kezzya

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/14714

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
