### ISSUE TITLE
thread.start

### ISSUE THREAD

**Issue by proff** [dotnet/docs.ru-ru#255]
Thread.Start - wasm

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f6487cae-3320-584d-6c27-fc712ec03e72
* Version Independent ID: 846981e7-bc47-0df8-8621-22282de18ef3
* Content: [Неподдерживаемые API в .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/compatibility/unsupported-apis#feedback)
* Content Source: [docs/core/compatibility/unsupported-apis.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/compatibility/unsupported-apis.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @proff
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @proff,

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by MSDN-WhiteKnight** [comment]
@ticianaciminari  Proff is probably trying to tell that [threading is not supported under Blazor Web assembly in ASP.NET Core](https://github.com/dotnet/aspnetcore/issues/14253), but this information is not mentioned on this page. This issue should probably be transferred to [dotnet/docs](https://github.com/dotnet/docs) repository, to update english page first. Although this page is under ".NET Framework to .NET Core" section, and .NET Framework never supported Web Assembly, so i wonder is it a good place to document this.

**Comment by proff** [comment]
yes, i mean threading is not supported by client-side blazor. I came to the page from other site and the title is not clear what it is ".NET Framework to .NET Core" section

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/dotnet-api-docs #3901](https://github.com/dotnet/dotnet-api-docs/issues/3901) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/dotnet-api-docs #3902](https://github.com/dotnet/dotnet-api-docs/issues/3902) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @proff, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/3901. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
