### ISSUE TITLE
'Pull request' literal translation to Russian

### ISSUE THREAD

**Issue by BarkhatovN** [dotnet/docs.ru-ru#265]
Hi everyone!
![image](https://user-images.githubusercontent.com/26570215/77584817-832c1000-6ef4-11ea-9fdc-57647b301161.png)
The "cc" should be "ss".
Thank you!

**Comment by srvbpigh** [comment]
Hello, @BarkhatovN
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @BarkhatovN 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Can you please provide the URL where you found this issue?

Kind regards, 

Microsoft DOCS International Team

**Comment by BarkhatovN** [comment]
https://docs.microsoft.com/ru-ru/dotnet/standard/base-types/custom-date-and-time-format-strings
Documetation in russian has issue. "cc" is not correct value to format seconds in that cell. Correct one is "ss".

**Comment by shamrik-dmitriy** [comment]
Hello! I Fixed it.
