### ISSUE TITLE
Maybe add simple example?

### ISSUE THREAD

**Issue by Devoleksiy** [dotnet/docs.ru-ru#285]
I need example)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [Форматы путей к файлам в системах Windows](https://docs.microsoft.com/ru-ru/dotnet/standard/io/file-path-formats#feedback)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @Devoleksiy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18372](https://github.com/dotnet/docs/issues/18372) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Devoleksiy, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/18372. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
